### ISSUE TITLE
Unclear how to use CRM get_by_id

### ISSUE THREAD

**Issue by gkorban** [HubSpot/hubspot-api-ruby#176]
It's not clear from the README or specs how to access the contacts API's READ method (GET /crm/v3/objects/contacts/{contactId}).

Here are some of the variations I tried:
> client = Hubspot::Client.new(access_token: 'access token')
=> #<Hubspot::Client:0x00005608130108a8 @params={:access_token=>'access token'}>
> opts = { properties: 'firstname,lastname,email'}
=> {:properties=>"firstname,lastname,email"}
> contact = client.crm.contacts.basic_api.get_by_id('12201', opts)
ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /.../vendor/bundle/ruby/2.7.0/gems/hubspot-api-client-15.0.2/lib/hubspot/discovery/base_api_client.rb:146:in `block (2 levels) in define_api_methods'

> contact = client.crm.contacts.basic_api.get_by_id('12201')
TypeError: no implicit conversion of Symbol into Integer
from /.../vendor/bundle/ruby/2.7.0/gems/hubspot-api-client-15.0.2/lib/hubspot/discovery/base_api_client.rb:148:in `[]'

> opts = { properties: 'firstname,lastname,email', id_property: 'email'}
=> {:properties=>"firstname,lastname,email", :id_property=>"email"}
> contact = client.crm.contacts.basic_api.get_by_id('user@domain.com', opts)
ArgumentError: wrong number of arguments (given 2, expected 0..1)
from /.../vendor/bundle/ruby/2.7.0/gems/hubspot-api-client-15.0.2/lib/hubspot/discovery/base_api_client.rb:146:in `block (2 levels) in define_api_methods'

I'm having the same challenge with retrieving companies.

What's the proper way to retrieve a single CRM object by ID?

**Comment by sequielo** [comment]
@gkorban I was able to do the following:
```
additional_props = ['firstname', 'emai', ...]
client.crm.contacts.basic_api.get_by_id(contact_id => id, properties: additional_props)
```

**Comment by Sokre95** [comment]
@gkorban You can take a look at examples here https://developers.hubspot.com/docs/api/crm/contacts

in case of get_by_id:

```ruby
api_client.crm.contacts.basic_api.get_by_id(contact_id: 123)
```

**Comment by gkorban** [comment]
@sequielo @Sokre95 Thanks! That's the info I was looking for!

**Comment by cesc1989** [comment]
Thanks @Sokre95 

For now on, I'm going to look at how it's supposed to be used in the docs instead of going to the source 😅

**Comment by averydev** [comment]
There should really be something in the docs for how to use this gem. It is not clear from the outside how any of this works.

**Comment by lrtherond** [comment]
The codegen stuff makes users' lives a living hell.

How do I retrieve a contact by email?

**Comment by Sokre95** [comment]
> The codegen stuff makes users' lives a living hell.
> 
> How do I retrieve a contact by email?

@lrtherond you can use search api for that: 

```ruby
body = {
  filterGroups: [{
    filters: [{
      propertyName: 'email',
      operator: 'EQ',
      value: email
    }]
  }],
  limit: 1
}

response = api_client.crm.contacts.search_api.do_search(body: body)
```

**Comment by lpar** [comment]
It would help if [the documentation](https://www.rubydoc.info/gems/hubspot-api-client/16.2.1/Hubspot/Crm/Deals/BasicApi#get_by_id-instance_method) was correct and mentioned the need for `symbol: value` rather than stating that you can just pass in an ID string.
