### ISSUE TITLE
snake_case attributes are wrongly being converted to camelCase

### ISSUE THREAD

**Issue by matiasleidemer** [HubSpot/hubspot-api-ruby#179]
I believe this is a regression caused by https://github.com/HubSpot/hubspot-api-ruby/pull/173. 

Properties sent using `snake_case` are being converted to `camelCase`. This is the response I get from the API after sending a property called `association_partner`:

```
{ "message" : "Invalid input JSON on line 1, column 86: Cannot construct instance of 
              `com.hubspot.inbounddb.publicobject.core.v2.SimplePublicObjectInput`, 
              problem: Names for properties should be lowercase and have less than 100 characters. 
              Invalid names: [associationPartner]"
```

Using version 15.0.1 works as expected.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @matiasleidemer 
Could you check the latest [version](https://github.com/HubSpot/hubspot-api-ruby/releases/tag/v16.2.1)?
Thanks.

**Comment by matiasleidemer** [comment]
@alzheltkovskiy-hubspot hey there, I tried updating to the latest version but one of my specs is failing:
```
Failures:

  1) Crm::Hubspot::Client::Deal#associated_contact calls the deals create method from the Hubspot client
     Failure/Error:
       client.crm.deals.associations_api.create(
         deal_id:,
         to_object_type: 'Contact',
         to_object_id: contact_id,
         association_type: 'deal_to_contact'
       )

     ArgumentError:
       Missing the required parameter 'association_spec' when calling AssociationsApi.create
     # /gems/ruby/3.1.0/gems/hubspot-api-client-16.4.0/lib/hubspot/codegen/crm/deals/api/associations_api.rb:138:in `create_with_http_info'
     # /gems/ruby/3.1.0/gems/hubspot-api-client-16.4.0/lib/hubspot/codegen/crm/deals/api/associations_api.rb:108:in `create'
     # /gems/ruby/3.1.0/gems/hubspot-api-client-16.4.0/lib/hubspot/discovery/base_api_client.rb:90:in `public_send'
     # /gems/ruby/3.1.0/gems/hubspot-api-client-16.4.0/lib/hubspot/discovery/base_api_client.rb:90:in `call_api'
     # /gems/ruby/3.1.0/gems/hubspot-api-client-16.4.0/lib/hubspot/discovery/base_api_client.rb:167:in `block (2 levels) in define_api_methods'
     # ./lib/crm/hubspot/client/deal.rb:34:in `associate_contact'
```

I have no idea what the `association_spec` parameter is, and I couldn't find any references on what to provide there.
