### ISSUE TITLE
Rails server fails to Start.

### ISSUE THREAD

**Issue by AmanRelan** [HubSpot/hubspot-api-ruby#29]
I am using this gem within the rails development environment and installed it by adding it to my gemfile and then `bundle install` my way through it. And then afterwards, on trying to start the rails server, it throws an error

Full Error Log: 

```
Traceback (most recent call last):
	59: from bin/rails:3:in `<main>'
	58: from bin/rails:3:in `load'
	57: from /Users/xyz/Projects/Example/bin/spring:15:in `<top (required)>'
	56: from /Users/xyz/Projects/Example/bin/spring:15:in `require'
	55: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	54: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	53: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	52: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	51: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	50: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	49: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	48: from /Users/xyz/Projects/Example/bin/rails:9:in `<top (required)>'
	47: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	46: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	45: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	44: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	43: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	42: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	41: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	40: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	39: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
	38: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
	37: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
	36: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	35: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	33: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `perform'
	32: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:138:in `tap'
	31: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.2/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	30: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	29: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	28: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	27: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	26: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	25: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	24: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	23: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	22: from /Users/xyz/Projects/Example/config/application.rb:20:in `<main>'
	21: from /Users/xyz/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
	20: from /Users/xyz/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
	19: from /Users/xyz/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
	18: from /Users/xyz/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
	17: from /Users/xyz/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
	16: from /Users/xyz/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	15: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	14: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	13: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	12: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	11: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	10: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/hubspot-api-client-2.3.2/lib/hubspot-api-client.rb:23:in `<main>'
	 9: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
	 8: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 7: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
	 6: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 5: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 4: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 3: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 2: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 1: from /Users/xyz/.rvm/gems/ruby-2.6.3/gems/hubspot-api-client-2.3.2/lib/hubspot/codegen/oauth/api_client.rb:19:in `<main>'
/Users/xyz/.rvm/gems/ruby-2.6.3/gems/hubspot-api-client-2.3.2/lib/hubspot/codegen/oauth/api_client.rb:20:in `<module:Hubspot>': OAuth is not a module (TypeError)
```

**Comment by ErmolkinVlad** [comment]
Can you show your `application.rb` file?
Did you try to name your class OAuth?

**Comment by AmanRelan** [comment]
> Did you try to name your class OAuth?
No My class is not name `OAuth`

My Application.rb is pretty basic

```
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_mailbox/engine"
require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module AuditHub
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.0

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    # Don't generate system test files.
    config.generators.system_tests = nil
  end
end

```

**Comment by ErmolkinVlad** [comment]
Can you also send your Gemfile please?

**Comment by AmanRelan** [comment]
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'mysql2', '>= 0.4.4'
gem 'puma', '~> 4.1'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.2', require: false
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
	gem 'dotenv-rails'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "hubspot-ruby"
gem 'devise'
gem 'jquery-ui-rails'
gem 'stripe-rails'
gem 'faraday'
gem 'hubspot-api-client', '~> 2.3'
```

**Comment by ErmolkinVlad** [comment]
This bug occurs when you declare class with some name, and then trying to declare module with the same name. Rails doesn't allow to do that. And in other direction: if you have module and then create class with the same name, there will be an error.
In this case gem `hubspot-ruby` has class `OAuth`, but our gem `hubspot-api-client` has module named `OAuth`. So you need to remove old gem `hubspot-ruby` to solve this issue.

**Comment by AmanRelan** [comment]
Yes, it does make sense to me now. So, By any chance, I won't be able to use the features of both of them.. Thank you for this.
